"""Add coluna nome tabela de usuario

Revision ID: 9caaa9c2c752
Revises: 65c170e11229
Create Date: 2026-05-08 15:52:28.432057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9caaa9c2c752'
down_revision: Union[str, Sequence[str], None] = '65c170e11229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nome', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'nome')
    # ### end Alembic commands ###
